// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJAEgSiUCSFgxA_Zxo2JQ-g58lh4azEPk',
    appId: '1:587779278474:web:618962b58975cab5a00f73',
    messagingSenderId: '587779278474',
    projectId: 'wisdomwell-9a7ee',
    authDomain: 'wisdomwell-9a7ee.firebaseapp.com',
    storageBucket: 'wisdomwell-9a7ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3tbt1RThk5YGtMdAtYap_CqRMzbWirDI',
    appId: '1:587779278474:android:d23ba7f2f85a12f9a00f73',
    messagingSenderId: '587779278474',
    projectId: 'wisdomwell-9a7ee',
    storageBucket: 'wisdomwell-9a7ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHgR38zgW9gtAlfy8xvL1UjvSud5pBNVQ',
    appId: '1:587779278474:ios:f9953e518ebf9907a00f73',
    messagingSenderId: '587779278474',
    projectId: 'wisdomwell-9a7ee',
    storageBucket: 'wisdomwell-9a7ee.appspot.com',
    iosBundleId: 'com.wisdom-well.app.wisdomWell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHgR38zgW9gtAlfy8xvL1UjvSud5pBNVQ',
    appId: '1:587779278474:ios:f9953e518ebf9907a00f73',
    messagingSenderId: '587779278474',
    projectId: 'wisdomwell-9a7ee',
    storageBucket: 'wisdomwell-9a7ee.appspot.com',
    iosBundleId: 'com.wisdom-well.app.wisdomWell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJAEgSiUCSFgxA_Zxo2JQ-g58lh4azEPk',
    appId: '1:587779278474:web:d9d9dd83cb7e03e8a00f73',
    messagingSenderId: '587779278474',
    projectId: 'wisdomwell-9a7ee',
    authDomain: 'wisdomwell-9a7ee.firebaseapp.com',
    storageBucket: 'wisdomwell-9a7ee.appspot.com',
  );
}
